# Generated by Django 5.0.2 on 2024-04-12 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(choices=[('SA', 'Springfield Armory'), ('W', 'Winchester Repeating Arms'), ('HR', 'Harrington & Richardson Arms Co'), ('IH', 'International Harvester')], max_length=32)),
                ('month', models.CharField(max_length=16)),
                ('starting_serial', models.IntegerField()),
                ('ending_serial', models.IntegerField()),
            ],
        ),
    ]
