# Generated by Django 5.0.2 on 2024-04-12 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
