# Generated by Django 5.0.2 on 2024-12-31 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0002_receiver_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpRod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(choices=[('SA', 'Springfield Armory'), ('W', 'Winchester Repeating Arms')], max_length=32)),
                ('drawing_number', models.CharField(max_length=20)),
                ('starting_serial', models.PositiveIntegerField()),
                ('ending_serial', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='receiver',
            name='maker',
            field=models.CharField(choices=[('SA', 'Springfield Armory'), ('W', 'Winchester Repeating Arms')], max_length=32),
        ),
    ]
