# Generated by Django 5.0.2 on 2025-01-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0003_oprod_alter_receiver_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='oprod',
            name='year_range_end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='oprod',
            name='year_range_start',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oprod',
            name='ending_serial',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='oprod',
            name='starting_serial',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
