# Generated by Django 5.0.2 on 2025-01-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0004_oprod_year_range_end_oprod_year_range_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oprod',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oprod',
            name='ending_serial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oprod',
            name='starting_serial',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oprod',
            name='year_range_end',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oprod',
            name='year_range_start',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
