# Generated by Django 5.0.2 on 2025-01-01 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0005_oprod_notes_alter_oprod_ending_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oprod',
            name='receivers',
            field=models.ManyToManyField(to='m1.receiver'),
        ),
    ]
