# Generated by Django 5.0.2 on 2025-01-06 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0006_oprod_receivers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oprod',
            name='receivers',
        ),
    ]
