# Generated by Django 5.0.2 on 2025-01-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0008_bolt'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletGuid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(choices=[('SA', 'Springfield Armory'), ('W', 'Winchester Repeating Arms'), ('IHC', 'International Harvester'), ('HR', 'Harrington & Richardson')], max_length=32)),
                ('drawing_number', models.CharField(max_length=30)),
                ('starting_serial', models.PositiveIntegerField(blank=True, null=True)),
                ('ending_serial', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hammer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(choices=[('SA', 'Springfield Armory'), ('W', 'Winchester Repeating Arms'), ('IHC', 'International Harvester'), ('HR', 'Harrington & Richardson')], max_length=32)),
                ('drawing_number', models.CharField(max_length=30)),
                ('starting_serial', models.PositiveIntegerField(blank=True, null=True)),
                ('ending_serial', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Safety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(choices=[('SA', 'Springfield Armory'), ('W', 'Winchester Repeating Arms'), ('IHC', 'International Harvester'), ('HR', 'Harrington & Richardson')], max_length=32)),
                ('drawing_number', models.CharField(max_length=30)),
                ('starting_serial', models.PositiveIntegerField(blank=True, null=True)),
                ('ending_serial', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(choices=[('SA', 'Springfield Armory'), ('W', 'Winchester Repeating Arms'), ('IHC', 'International Harvester'), ('HR', 'Harrington & Richardson')], max_length=32)),
                ('drawing_number', models.CharField(max_length=30)),
                ('starting_serial', models.PositiveIntegerField(blank=True, null=True)),
                ('ending_serial', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(choices=[('SA', 'Springfield Armory'), ('W', 'Winchester Repeating Arms'), ('IHC', 'International Harvester'), ('HR', 'Harrington & Richardson')], max_length=32)),
                ('drawing_number', models.CharField(max_length=30)),
                ('starting_serial', models.PositiveIntegerField(blank=True, null=True)),
                ('ending_serial', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerHousing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(choices=[('SA', 'Springfield Armory'), ('W', 'Winchester Repeating Arms'), ('IHC', 'International Harvester'), ('HR', 'Harrington & Richardson')], max_length=32)),
                ('drawing_number', models.CharField(max_length=30)),
                ('starting_serial', models.PositiveIntegerField(blank=True, null=True)),
                ('ending_serial', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
    ]
