# Generated by Django 5.0.2 on 2025-01-23 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0011_cartouche'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartouche',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
