# Generated by Django 5.0.2 on 2025-01-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0012_cartouche_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Srs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.PositiveIntegerField()),
                ('firearm', models.CharField(choices=[('M1', 'M1 Garand'), ('M1903', 'M1903 Springfield')], max_length=32)),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.CharField(max_length=6)),
                ('usage', models.CharField(max_length=64)),
            ],
        ),
    ]
