# Generated by Django 5.0.2 on 2025-01-31 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0013_srs'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerhousing',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
