# Generated by Django 5.0.2 on 2025-02-01 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0014_triggerhousing_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='hammer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='safety',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trigger',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triggerguard',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
