# Generated by Django 5.0.2 on 2025-02-03 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0015_hammer_notes_safety_notes_trigger_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRSVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='srs',
            name='srs_volume',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='m1.srsvolume'),
        ),
    ]
