# Generated by Django 5.0.2 on 2025-02-10 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0016_srsvolume_srs_srs_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maker', models.CharField(choices=[('SA', 'Springfield Armory'), ('W', 'Winchester Repeating Arms'), ('IHC', 'International Harvester'), ('HR', 'Harrington & Richardson')], max_length=32)),
                ('drawing_number', models.CharField(max_length=16)),
                ('starting_serial', models.PositiveIntegerField(blank=True, null=True)),
                ('ending_serial', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
