# Generated by Django 5.0.2 on 2025-02-22 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0019_firearm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srs',
            name='firearm',
        ),
    ]
