# Generated by Django 5.0.2 on 2025-02-22 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0020_remove_srs_firearm'),
    ]

    operations = [
        migrations.AddField(
            model_name='srs',
            name='firearm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='m1.firearm'),
        ),
    ]
