# Generated by Django 5.0.2 on 2026-08-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('m1', '0021_srs_firearm'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.CharField(blank=True, choices=[('production', 'Production History'), ('military', 'Military Videos'), ('maintenance', 'Rifle Maintenance')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='video',
            constraint=models.UniqueConstraint(fields=('category', 'order'), name='unique_category_order'),
        ),
    ]
